[package]
name = "orz_os"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "orz_os"
test = false
bench = false

[profile.release]
debug = true

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
